name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        cabal: ["3.2.0.0"]
        ghc:
          - "8.10.2"

    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        repository: berberman/arch-hs

    - uses: actions/setup-haskell@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: Build
      run: |
        cabal update
        cabal v2-build
        cabal v2-haddock --builddir="$dir" --haddock-for-hackage --enable-doc
    - uses: actions/upload-artifact@v2
      name: Upload
      with:
        name: docs
        path: arch-hs-0.1.1.0-docs.tar.gz
    
